ARG BASE_IMAGE=zcx-pairec-brpc-sdk:v1
ARG ENABLE_TRTLLM_CPP=OFF
ARG ENABLE_DATASYSTEM_KV_PROBE=OFF
ARG ENABLE_BRPC_UB=OFF
ARG TRTLLM_INCLUDE_DIR=
ARG TRTLLM_LIBRARY=
ARG TRTLLM_PLUGIN_LIBRARY=
ARG TRTLLM_EXTRA_LIBS=
ARG TRTLLM_CUDA_INCLUDE_DIR=
ARG CUDA_DRIVER_LIBRARY=
ARG DATASYSTEM_INCLUDE_DIR=
ARG DATASYSTEM_LIBRARY=
ARG SOURCE_COMMIT=unknown

FROM ${BASE_IMAGE} AS build

ARG ENABLE_TRTLLM_CPP
ARG ENABLE_DATASYSTEM_KV_PROBE
ARG ENABLE_BRPC_UB
ARG TRTLLM_INCLUDE_DIR
ARG TRTLLM_LIBRARY
ARG TRTLLM_PLUGIN_LIBRARY
ARG TRTLLM_EXTRA_LIBS
ARG TRTLLM_CUDA_INCLUDE_DIR
ARG CUDA_DRIVER_LIBRARY
ARG DATASYSTEM_INCLUDE_DIR
ARG DATASYSTEM_LIBRARY
ARG SOURCE_COMMIT

# The TRT/DataSystem base images can carry LD_PRELOAD paths from interactive
# validation containers. brpc image builds should not inherit those paths.
ENV LD_PRELOAD=""

WORKDIR /src

COPY proto /src/proto
COPY cpp/brpc_gateway /src/cpp/brpc_gateway
COPY cpp/brpc_ub_probe /src/cpp/brpc_ub_probe
COPY cpp/kvc_burst /src/cpp/kvc_burst

RUN unset LD_PRELOAD \
 && cmake -S /src/cpp/brpc_gateway -B /tmp/brpc-gateway-build \
      -DCMAKE_BUILD_TYPE=Release \
      -DPAIREC_ENABLE_TRTLLM_CPP="${ENABLE_TRTLLM_CPP}" \
      -DPAIREC_ENABLE_DATASYSTEM_KV_PROBE="${ENABLE_DATASYSTEM_KV_PROBE}" \
      -DPAIREC_ENABLE_BRPC_UB="${ENABLE_BRPC_UB}" \
      -DTRTLLM_INCLUDE_DIR="${TRTLLM_INCLUDE_DIR}" \
      -DTRTLLM_LIBRARY="${TRTLLM_LIBRARY}" \
      -DTRTLLM_PLUGIN_LIBRARY="${TRTLLM_PLUGIN_LIBRARY}" \
      -DTRTLLM_EXTRA_LIBS="${TRTLLM_EXTRA_LIBS}" \
      -DTRTLLM_CUDA_INCLUDE_DIR="${TRTLLM_CUDA_INCLUDE_DIR}" \
      -DCUDA_DRIVER_LIBRARY="${CUDA_DRIVER_LIBRARY}" \
      -DDATASYSTEM_INCLUDE_DIR="${DATASYSTEM_INCLUDE_DIR}" \
      -DDATASYSTEM_LIBRARY="${DATASYSTEM_LIBRARY}" \
      -DPAIREC_SOURCE_COMMIT="${SOURCE_COMMIT}" \
 && cmake --build /tmp/brpc-gateway-build -j"$(nproc)" \
 && cmake --install /tmp/brpc-gateway-build --prefix /opt/pairec-brpc

FROM ${BASE_IMAGE}

ENV LD_PRELOAD=""

COPY --from=build /opt/pairec-brpc /opt/pairec-brpc

ENV PATH="/opt/pairec-brpc/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/lib/python3.11/site-packages/yr/datasystem/lib:/usr/local/lib:/usr/local/lib64:/usr/lib64:/usr/lib:${LD_LIBRARY_PATH}"

EXPOSE 18100 18103 18201 18211 18213

ENTRYPOINT ["/opt/pairec-brpc/bin/brpc_gateway"]
CMD ["--listen_port=18100", "--http_forward=127.0.0.1:18000"]
