ARG BASE_IMAGE=zcx-pairec-brpc-sdk:v1
ARG ENABLE_TRTLLM_CPP=OFF
ARG TRTLLM_INCLUDE_DIR=
ARG TRTLLM_LIBRARY=
ARG TRTLLM_EXTRA_LIBS=
ARG TRTLLM_CUDA_INCLUDE_DIR=
ARG CUDA_DRIVER_LIBRARY=
ARG NVML_LIBRARY=

FROM ${BASE_IMAGE} AS build

ARG ENABLE_TRTLLM_CPP
ARG TRTLLM_INCLUDE_DIR
ARG TRTLLM_LIBRARY
ARG TRTLLM_EXTRA_LIBS
ARG TRTLLM_CUDA_INCLUDE_DIR
ARG CUDA_DRIVER_LIBRARY
ARG NVML_LIBRARY

# The TRT/DataSystem base images can carry LD_PRELOAD paths from interactive
# validation containers. brpc image builds should not inherit those paths.
ENV LD_PRELOAD=""

WORKDIR /src

COPY proto /src/proto
COPY cpp/brpc_gateway /src/cpp/brpc_gateway

RUN unset LD_PRELOAD \
 && cmake -S /src/cpp/brpc_gateway -B /tmp/brpc-gateway-build \
      -DCMAKE_BUILD_TYPE=Release \
      -DPAIREC_ENABLE_TRTLLM_CPP="${ENABLE_TRTLLM_CPP}" \
      -DTRTLLM_INCLUDE_DIR="${TRTLLM_INCLUDE_DIR}" \
      -DTRTLLM_LIBRARY="${TRTLLM_LIBRARY}" \
      -DTRTLLM_EXTRA_LIBS="${TRTLLM_EXTRA_LIBS}" \
      -DTRTLLM_CUDA_INCLUDE_DIR="${TRTLLM_CUDA_INCLUDE_DIR}" \
      -DCUDA_DRIVER_LIBRARY="${CUDA_DRIVER_LIBRARY}" \
      -DNVML_LIBRARY="${NVML_LIBRARY}" \
 && cmake --build /tmp/brpc-gateway-build -j"$(nproc)" \
 && cmake --install /tmp/brpc-gateway-build --prefix /opt/pairec-brpc

FROM ${BASE_IMAGE}

ENV LD_PRELOAD=""

COPY --from=build /opt/pairec-brpc /opt/pairec-brpc

ENV PATH="/opt/pairec-brpc/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/lib:/usr/local/lib64:/usr/lib64:/usr/lib:${LD_LIBRARY_PATH}"

EXPOSE 18100

ENTRYPOINT ["/opt/pairec-brpc/bin/brpc_gateway"]
CMD ["--listen_port=18100", "--http_forward=127.0.0.1:18000"]
