#!/usr/bin/env python3
"""Export a compact tokenizer config for the C++ brpc TRT-LLM backend.

The native C++ backend only needs the fixed recommendation prompt fragments and
the semantic special-token ids. Keeping this file generated from the same
HuggingFace tokenizer used during TRT export avoids a partial C++ tokenizer
implementation drifting away from Python.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from transformers import AutoTokenizer


PROMPT_PREFIX = "用户按时间顺序点击过以下商品：\n"
ITEM_SEPARATOR = ","
PROMPT_SUFFIX = "\n请预测用户下一个可能点击的商品："


def format_ids(token_ids: Iterable[int]) -> str:
    return " ".join(str(int(token_id)) for token_id in token_ids)


def encode_fragment(tokenizer, text: str, name: str) -> list[int]:
    token_ids = tokenizer.encode(text, add_special_tokens=False)
    if not token_ids:
        raise RuntimeError(f"{name} encoded to an empty token list")
    return [int(token_id) for token_id in token_ids]


def semantic_token_id(tokenizer, token: str) -> int:
    token_id = tokenizer.convert_tokens_to_ids(token)
    if token_id is None:
        raise RuntimeError(f"semantic token is missing from tokenizer: {token}")
    unk_id = tokenizer.unk_token_id
    if unk_id is not None and int(token_id) == int(unk_id):
        raise RuntimeError(
            f"semantic token resolved to unk_token_id={unk_id}: {token}. "
            "Use the tokenizer exported with semantic special tokens."
        )
    return int(token_id)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--tokenizer-dir",
        default="./exported/qwen3_rec",
        help="Directory containing the exported HuggingFace tokenizer",
    )
    parser.add_argument(
        "--output",
        default="./exported/qwen3_rec/pairec_cpp_tokenizer.txt",
        help="Output path consumed by brpc_inference_server --trt_tokenizer_config_path",
    )
    parser.add_argument("--num-quantizers", type=int, default=4)
    parser.add_argument("--vocab-size", type=int, default=256)
    args = parser.parse_args()

    tokenizer = AutoTokenizer.from_pretrained(args.tokenizer_dir, trust_remote_code=True)
    eos_id = tokenizer.eos_token_id
    if eos_id is None:
        raise RuntimeError("tokenizer.eos_token_id is not set")
    pad_id = tokenizer.pad_token_id
    if pad_id is None:
        pad_id = eos_id

    prefix_ids = encode_fragment(tokenizer, PROMPT_PREFIX, "prompt prefix")
    separator_ids = encode_fragment(tokenizer, ITEM_SEPARATOR, "item separator")
    suffix_ids = encode_fragment(tokenizer, PROMPT_SUFFIX, "prompt suffix")

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as f:
        f.write("# Generated by scripts/export_cpp_trt_tokenizer_config.py\n")
        f.write(f"# tokenizer_dir {Path(args.tokenizer_dir).resolve()}\n")
        f.write(f"# prompt_prefix {PROMPT_PREFIX!r}\n")
        f.write(f"# item_separator {ITEM_SEPARATOR!r}\n")
        f.write(f"# prompt_suffix {PROMPT_SUFFIX!r}\n")
        f.write(f"eos_id {int(eos_id)}\n")
        f.write(f"pad_id {int(pad_id)}\n")
        f.write(f"prefix {format_ids(prefix_ids)}\n")
        f.write(f"separator {format_ids(separator_ids)}\n")
        f.write(f"suffix {format_ids(suffix_ids)}\n")
        for layer in range(args.num_quantizers):
            for value in range(args.vocab_size):
                token = f"<s{layer}_{value}>"
                f.write(f"semantic {layer} {value} {semantic_token_id(tokenizer, token)}\n")

    print(f"wrote {output}")
    print(f"prefix_tokens={len(prefix_ids)} separator_tokens={len(separator_ids)} suffix_tokens={len(suffix_ids)}")
    print(f"semantic_tokens={args.num_quantizers * args.vocab_size}")
    print(f"eos_id={int(eos_id)} pad_id={int(pad_id)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
